# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hq6bUR_7m_JQMpwIMve-boIEYlWzRfiD
"""

import os
import pandas as pd
#create folders
folders=["customer","Employee", "Loan"]
for folder in folders:
  os.makedirs(folder, exist_ok=True)

  #customer
customer = pd.DataFrame({
      "Name":["Alish", "Ram", "Hari", "Shyam"],
      "Account":[1001, 1002, 1003, 1004],
      "Balance":["5000","6000","7000","80000"]

  })
customer.to_excel("Customer/customer.xlsx", index=False)

  #employee
employee = pd.DataFrame({
    "Name": ["Bikash", "Sita", "Rita"],
    "Salary": [45000, 60000, 55000],
    "Department": ["IT", "Finance", "HR"]
})
employee.to_excel("Employee/employee.xlsx", index=False)

# ---------------- Loan ----------------
loan = pd.DataFrame({
    "Name": ["Alish", "Ram", "Hari"],
    "Loan": [200000, 500000, 100000],
    "Status": ["Approved", "Pending", "Approved"]
})

loan.to_excel("Loan/loan.xlsx", index=False)

print("Folders and Excel files created successfully.")

"""# New section"""
